'use strict';

/**
 * Turns Lighthouse's third-party-summary audit into the app/script impact
 * rows the spec's differentiator feature needs (requests/size/impact by
 * installed app). Lighthouse groups by "entity" (root domain heuristics);
 * we pass its label through as-is as the initial "app name" - a future pass
 * can cross-reference this against the shop's actual installed-apps list
 * (via Admin GraphQL) to get real app names instead of domain guesses.
 */

// Shopify's own infrastructure, not a merchant-installed app - these are
// injected by Shopify itself via content_for_header (Shop Pay, checkout,
// core analytics), so the literal script tag never appears anywhere in the
// theme's own Liquid source for ScriptImpactActionService to find, and
// disabling/delaying core platform functionality isn't something an app
// should offer even where it were technically possible.
const PLATFORM_HOSTS = [
  'cdn.shopify.com',
  'shop.app',
  'shopifycloud.com',
  'monorail-edge.shopifysvc.com',
  'checkout.shopify.com',
];

function isPlatformUrl(url) {
  if (!url) return false;

  try {
    const host = new URL(url).hostname;

    return PLATFORM_HOSTS.some((platformHost) => host === platformHost || host.endsWith(`.${platformHost}`));
  } catch {
    return false;
  }
}

// SpeedPilot's own interceptor delivery script (see InterceptorController /
// the "SpeedPilot Advanced Delay" app embed) is itself fetched by the
// storefront and gets picked up by Lighthouse's third-party-summary audit
// like any other request - without this, the app would flag its own script
// as something the merchant should "fix". Excluded outright, not just
// badged, since it isn't a third party the merchant installed at all.
const OWN_HOSTS = ['speedpilot-production.up.railway.app'];

function isOwnUrl(url) {
  if (!url) return false;

  try {
    const host = new URL(url).hostname;

    return OWN_HOSTS.some((ownHost) => host === ownHost || host.endsWith(`.${ownHost}`));
  } catch {
    return false;
  }
}

// Tracking pixels (Facebook's "extended matching" params are the worst
// offender - hundreds of comma-separated numbers in a single query param)
// routinely produce URLs well past a thousand characters, and none of that
// query string is ever static from one page load to the next anyway - it's
// runtime-generated by the tracker's own JS, never present verbatim in the
// theme's source. Stripping it: (1) keeps script_url stable across scans,
// which app_impacts/interceptor-delay matching and audit-to-audit diffing
// both depend on exact-matching against, and (2) is what actually can show
// up literally in a theme file for ThemeAssetLocatorService to find - the
// full runtime URL with its dynamic params never will.
function stripVolatileParams(url) {
  if (!url) return url;

  try {
    const parsed = new URL(url);

    return `${parsed.origin}${parsed.pathname}`;
  } catch {
    return url;
  }
}

// Liquid's `replace` filter does a literal substring match, so the search
// text handed to it has to be exactly what Shopify actually rendered - not
// a reconstructed guess. This finds the real `src="..."`/`href="..."`
// attribute (if any) that literally contains the flagged URL in the page's
// own server-rendered HTML, and returns that exact substring verbatim.
// Query params/hashes on the flagged URL itself can differ from what's in
// the markup (stripVolatileParams already strips them off `url`), so this
// matches on the origin+pathname prefix, not the full string.
//
// Scoped to <head>...</head> only, not the whole page - confirmed live
// against a real store that this matters: `content_for_header` is always
// rendered inside <head>, but a Theme App Extension "app embed" block with
// `target: "body"` (how most apps deliver scripts on Online Store 2.0
// themes - Shopify's own guidance is that the legacy Script Tag API, which
// is what actually lands in content_for_header, only works reliably on
// vintage themes now) renders near </body> instead. A whole-page search
// found PayPal's SDK script as a literal match this way, but it sits deep
// in <body> - nothing a content_for_header `replace` chain could ever
// reach, even though the text is genuinely on the page. Scoping to <head>
// isn't a perfect guarantee (a target:"head" app embed is also in <head>
// but still outside content_for_header specifically), but it eliminates
// this confirmed, most severe class of false positive.
function findStaticMatch(rawHtml, url) {
  if (!rawHtml || !url) return null;

  const headEnd = rawHtml.search(/<\/head\s*>/i);
  const head = headEnd === -1 ? rawHtml : rawHtml.slice(0, headEnd);

  const escaped = url.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const pattern = new RegExp(`(?:src|href)\\s*=\\s*["'][^"']*${escaped}[^"']*["']`, 'i');
  const match = head.match(pattern);

  return match ? match[0] : null;
}

function thirdPartyImpacts(lhr, rawHtml) {
  const summary = lhr.audits?.['third-party-summary'];
  const items = summary?.details?.items ?? [];

  return items
    .filter((item) => !isOwnUrl(stripVolatileParams(item.subItems?.items?.[0]?.url ?? null)))
    .map((item) => {
      const bytes = item.transferSize ?? 0;
      const blockingMs = item.blockingTime ?? item.mainThreadTime ?? 0;
      const rawUrl = item.subItems?.items?.[0]?.url ?? null;
      const url = stripVolatileParams(rawUrl);

      return {
        name: item.entity?.text ?? item.entity ?? 'Unknown script',
        url,
        requests: item.subItems?.items?.length ?? 1,
        bytes,
        blockingMs,
        impactLevel: impactLevelFor(bytes, blockingMs),
        isPlatform: isPlatformUrl(url),
        staticMatch: findStaticMatch(rawHtml, url),
      };
    });
}

function impactLevelFor(bytes, blockingMs) {
  if (bytes > 300_000 || blockingMs > 250) return 'high';
  if (bytes > 100_000 || blockingMs > 100) return 'medium';
  return 'low';
}

module.exports = { thirdPartyImpacts };
